model:
  path: configs/sd/v1-inference.yaml
  type: SD
  conditional: true
  t_eps: null
  guidance_scale: null
  prompts_path: data/coco_captions.txt 
  # Use coco_captions from https://github.com/vinhsuhi/LD3/blob/ec1bf603fb19696966ca30198ed209ae6488a3e5/data/coco_captions.txt

dataset:
  teacher_pkl: data/teachers/sd-v1/nfe=5/dataset.pkl
  use_latents: true
  use_condition: true
  train_size: null
  dataset_shift: 0
  batch_size: 2
  validation_batch_size: 2
  validation_size: 4
  size_vis: 4
  num_workers: 10

teacher_solver_config:
  steps: null
  order: 3
  t_eps: 0.001
  guidance_scale: 7.5

student_solver_config:
  steps: null
  order: null
  t_eps: 0.00001
  t_parametrization: linear # mu_logit # linear # content_aware 
  use_theory_coef: true
  guidance_scale: 7.5
  t_couple_requires_grad: false
  a_requires_grad: false
  c_requires_grad: false

  loss_config:
    loss_type: null
    loss_key: loss_l1_latents
    disc_weight: 1
    disc_type: latent_4
    disc_lr: 0.001

training:
  n_iters: 5000
  lr: 0.0000001
  iters_to_accumulate: 2
  ema_decay: 0.999

logging:
  project_name: GAS
  eval_freq: 100
  checkpoint_freq: 100
  log_weights_freq: 100
  run_name: "coco_linear_train_4_even_smaller_lr"
  # run_name: "coco_baseline_test"
  mode: online
  workspace: govzman
  project_name: test_GAS
