steps: 4
order: 3
t_eps: 0.001
latent_channels: 4
text_embed_dim: 768
t_couple_parametrization: diff   # diff | linear | mlp | film_mlp | prompt_noise_film_mlp | stepwise

t_parametrization: diff          # diff | linear | mlp | transformer | film_mlp | prompt_noise_film_mlp
a_parametrization: diff # diff | linear | mlp | transformer | stepwise
c_parametrization: diff # diff | linear | mlp | transformer | stepwise

use_theory_coef: true
guidance_scale: 7.5
t_requires_grad: true
t_couple_requires_grad: true
a_requires_grad: true
c_requires_grad: true
