steps: 4
order: 3
t_eps: 0.001
t_parametrization: mu_logit # linear
a_parametrization: diff # diff | linear | mlp | transformer
c_parametrization: diff # diff | linear | mlp | transformer
use_theory_coef: true
guidance_scale: 7.5
t_requires_grad: false
t_couple_requires_grad: false
a_requires_grad: true
c_requires_grad: false
