teacher_pkl: "data/teachers/sd-v1/nfe=5/dataset.pkl"
use_latents: true
use_condition: true
train_size: 1
batch_size: 1
dataset_shift: 0
validation_batch_size: 1
validation_size: 1
size_vis: 1
num_workers: 2

