teacher_pkl: "data/teachers/sd-v1/synt3/dataset.pkl"
use_latents: true
use_condition: true
train_size: 96
batch_size: 2
dataset_shift: 0
validation_batch_size: 2
validation_size: 4
size_vis: 4
num_workers: 1

