defaults:
  - model: coco
  - scheduler_model: scheduler_transformer
  - writer: cometml
  - datasets: coco
  - student_solver: sd_student_default
  - teacher_solver: sd_teacher_default

loss_config:
  loss_type: "GS"
  loss_key: loss_l1_latents
  disc_weight: 1
  disc_type: latent_4
  disc_lr: 0.00001

# model: src/model/coco
outdir: "data/teachers/sd-v1/synt6"
seeds: "00000-00099"
max_batch_size: 1
checkpoint_path: null
create_dataset: true
device: cuda

synthetic_gs_dataset:
  enabled: true
  count: 100
  nfe: 5
  order: 3
  coef_std: 0.01
  t_couple_std: 0.01
  include_t_couple: true
  include_timesteps: false
  t_std: 0.005
  prompts: null