model:
  path: configs/ldm/model_cin256-v2.yaml
  type: LDM
  conditional: true
  t_eps: null
  guidance_scale: null

dataset:
  teacher_pkl: data/teachers/ldm/cin256-v2/dataset.pkl
  use_latents: true
  use_condition: true
  train_size: null
  batch_size: 1
  validation_batch_size: 1
  validation_size: 2
  size_vis: 2
  num_workers: 10

teacher_solver_config:
  steps: 10 
  order: 3 
  time_type: time_quadratic
  variant: bh2
  t_eps: 0.001
  guidance_scale: 2.

student_solver_config:
  steps: null
  order: null
  t_eps: 0.001
  t_parametrization: mu_logit
  use_theory_coef: true
  guidance_scale: 2.
  a_requires_grad: false
  c_requires_grad: false

  loss_config:
    loss_type: null
    loss_key: loss_l1_latents
    disc_weight: 1
    disc_type: latent_3
    disc_lr: 0.00001

training:
  n_iters: 5000
  lr: 0.001
  iters_to_accumulate: 1
  ema_decay: 0.999

logging:
  project_name: GAS
  eval_freq: 100
  checkpoint_freq: 100
  log_weights_freq: 10
  run_name: "cin256_NFE=8_ts=8_no_grad_class_emb + tanh + scaler"
  mode: online
  workspace: govzman
  project_name: test_GAS
  